name: Build and Push application to Google Cloud Run

on:
    workflow_dispatch:
    push:
        branches:
            - "main"

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

    # # LOS PASOS QUE VIENEN ABAJO NO HACEN FALTA CON UNA CUENTA DE SERVICIO
    # # PERO CON EN TECO NO TENGO PERMISOS PARA CREARLA, USO MIS CREDENCIALES DE GCLOUD
    
    #   - 
    #     name: 'Set up Cloud SDK'
    #     uses: 'google-github-actions/setup-gcloud@v1'

    #   - 
    #     name: Authenticate with Google Cloud
    #     run: gcloud auth application-default login

    # ESTO ES PARA AUTENTICARSE CON UNA CUENTA DE SERVICIO! LO QUE ESTA ARRIBA ES PARA UNA CUENTA CON CREDENCIALES 
      - 
        id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - 
        name: Build Docker Image
        run: |
            docker build -f Dockerfile -t todolist-app .
            docker tag todolist-app ${{ secrets.CONTAINER_IMAGE_URL }}:latest
            docker tag todolist-app ${{ secrets.CONTAINER_IMAGE_URL }}:v1
            gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev
            docker push ${{ secrets.CONTAINER_IMAGE_URL }} --all-tags

            
      -
        name: Deploy container to GCloud Run
        run: |
            gcloud run deploy serverless-py-run \
            --image=${{ secrets.CONTAINER_IMAGE_URL }}:latest \
            --allow-unauthenticated \
            --region=${{ secrets.REGION }} \
            --project=${{ secrets.PROJECT_ID }}
        


        

